### DISCUSSION TITLE
Stylesheet / theme adjustments

### DISCUSSION THREAD

**Discussion by wolandark** [ezra-bible-app/ezra-bible-app#1117] [Development]
Hi there,
Any idea where this lime color in the darkmode highlight is being set from?

![image](https://github.com/user-attachments/assets/82c63608-c14f-4105-a407-fbefc6d96091)
![image](https://github.com/user-attachments/assets/9d8d6ab6-ce5b-4464-bbb8-482918b89a8e)

### My main.css

<details> <summary> expand main.css </summary>

```css
:root {
  --accent-color: #2779aa;
  --accent-color-darkmode: #74c7ec;
  --background-color: #f2e5bc;
  --background-color-darker: #e6e9eb;
  --widget-bg-color: #eeeeee;
  --text-color: #282828;
  --text-color-red: firebrick;
  --text-color-red-darkmode: #f38ba8;

  --highlight-object-color: #afcdff;
  --highlight-object-color-dark: #a6adc8;

  --border-color: #dddddd;
  --border-radius: 6px;
  --area-border: 1px solid var(--border-color);

  --highlight-bg-color: #e4f1fb;
  --highlight-bg: var(--highlight-bg-color)
    url(images/ui-bg_glass_100_e4f1fb_1x400.png) 50% 50% repeat-x;
  --highlight-border-color: #74b2e2;
  --highlight-border: 1px solid var(--highlight-border-color);
  --highlight-color: var(--accent-color);

  --checkmark-success-color: LimeGreen;

  --button-color: #777;
  --button-color-dark: #aaa;
  --disabled-button-color: #bbbbbb;
}

:root body.darkmode--activated {
  --background-color: #1e1e2e;
  --background-color-darker: #171717;
  --widget-bg-color: #1e1e1e;
  --text-color: #cdd6f4;

  --border-color: #555555;

  --highlight-bg-color: #003147;
  --highlight-bg: var(--highlight-bg-color)
    url(jquery-ui/dark-hive/images/ui-bg_highlight-soft_33_003147_1x100.png) 50%
    50% repeat-x;
  --highlight-border-color: #0b93d5;
  --highlight-color: var(--text-color);

  --disabled-button-color: #555555;
}

```

</details>

Cheers and thanks for the great app.

**Comment by wolandark** [comment]
I just realized that the green fg color only exists when the dictionary module is selected.

**Comment by wolandark** [comment]
Never mind I found it! its the 
```
.darkmode--activated .strongs-current-verse w {
  color: lightgreen;
}
```
in main.css

**Reply by tobias-klein** [reply]
@wolandark Yes, that's it. I'm glad you found it! Out of curiosity: So you're trying to customize the theme/colors a bit? Do you suggest any general enhancements of the colors that should be applied for all users?

**Reply by wolandark** [reply]
Yes I'm customizing both the light and the dark themes for myself. 

So far I have a catppuccin-ish dark theme and a gruvbox-ish light theme going on.

<details> <summary> Expand Screenshots</summary>

![image](https://github.com/user-attachments/assets/3a95a1af-7f85-4d12-b295-a05e2332bb9d)
![image](https://github.com/user-attachments/assets/f518ecb6-a1ef-4208-86fc-f39f1f7713ca)

</details>



I would suggest the ability to read a custom `light.css` and `dark.css` to be added to ezra-bible-app. That way we could make many themes for users, and you know people love themes.

It would even be better if we could have more than two themes listed in the settings from custom css files at `xdg-home`. 

#### On another note, this is really bothering me:
![image](https://github.com/user-attachments/assets/c7953041-5353-42c9-8c82-77b3f4ff2ec3)
![image](https://github.com/user-attachments/assets/dba57059-bd78-43bb-adee-59937df7905f)

Do you see that the top of the next line is almost poking into the `ui-select-menu-status` field? That makes the ui feel somewhat clunky. 

adding these css rules seems to be working well for me.

```css
.ui-selectmenu-status {
    line-height: 1.4em;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```

![image](https://github.com/user-attachments/assets/59fdefd1-957a-4512-a103-496064e20e43)
![image](https://github.com/user-attachments/assets/05b33d53-1eb8-4e00-8998-a50cebc5737d)
![image](https://github.com/user-attachments/assets/976aa785-e99c-4efb-8ed6-c7965a3f3725)
![image](https://github.com/user-attachments/assets/82fadf01-70d4-40ff-8370-f7b3b7845040)
